name: makemkv
summary: Backup your Bluray and DVD discs
description: |
  Backup your Bluray and DVD discs

grade: stable
confinement: strict
adopt-info: makemkv-oss
base: core20
compression: lzo

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf

layout:
  /etc/java-11-openjdk:
    bind: $SNAP/etc/java-11-openjdk
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /usr/bin/java:
    symlink: $SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin/java
  /usr/bin/wget:
    bind-file: $SNAP/usr/bin/wget
  /usr/lib/jvm:
    bind: $SNAP/usr/lib/jvm
  $SNAP/usr/share/MakeMKV:
    bind: $SNAP_DATA/usr/share/MakeMKV

plugs:
  optical-write:
    interface: optical-drive
    write: true
  gtk-3-themes:
    default-provider: gtk-common-themes:gtk-3-themes
    interface: content
    target: $SNAP/data-dir/themes
  sound-themes:
    default-provider: gtk-common-themes:sound-themes
    interface: content
    target: $SNAP/data-dir/sounds
  icon-themes:
    default-provider: gtk-common-themes:icon-themes
    interface: content
    target: $SNAP/data-dir/icons

hooks:
  install:
    command-chain: [bin/desktop-launch]
    passthrough:
      environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib
  post-refresh:
    command-chain: [bin/desktop-launch]
    passthrough:
      environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib

apps:
  makemkv:
    command: usr/bin/makemkv
    command-chain:
    - bin/desktop-launch
    - bin/check-ld-cache
    - bin/makemkv-launch
    - bin/snapcraft-preload
    desktop: usr/share/applications/makemkv.desktop
    environment:
      FINAL_BINARY: $SNAP/usr/bin/makemkv
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - hardware-observe
    - home
    - network
    - opengl
    - optical-drive
    - optical-write
    - process-control
    - removable-media
    - unity7
    - wayland
    - x11

  makemkvcon:
    command: usr/bin/makemkvcon
    command-chain:
    - bin/check-ld-cache
    - bin/makemkv-launch
    - bin/snapcraft-preload
    environment:
      FINAL_BINARY: $SNAP/usr/bin/makemkvcon.real
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET
    plugs:
    - hardware-observe
    - home
    - network
    - optical-drive
    - optical-write
    - process-control
    - removable-media

parts:
  scripts:
    source: scripts
    plugin: dump
    organize:
      build-ld-cache: bin/build-ld-cache
      check-ld-cache: bin/check-ld-cache
      makemkv-launch: bin/makemkv-launch
    stage-packages:
    - rsync

  patches:
    source: patches
    plugin: dump
    prime: [-*]

  libav:
    source: https://ffmpeg.org/releases/ffmpeg-4.3.2.tar.xz
    plugin: autotools
    build-packages:
    - libfdk-aac-dev
    - yasm
    autotools-configure-parameters:
    - --prefix=/usr
    - --enable-static
    - --disable-shared
    - --enable-pic
    - --enable-libfdk-aac
    stage-packages:
    - libfdk-aac1
    - libxcb-shape0
    prime:
    - -**/*.a

  snapcraft-preload:
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
    - gcc
    - g++
    - on amd64:
      - gcc-multilib
      - g++-multilib
    stage-packages:
    - on amd64:
      - lib32stdc++6

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgtk2.0-0
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - qtwayland5
    - locales-all

  makemkv-oss:
    after: [patches, desktop-qt5, libav]
    plugin: autotools
    build-packages:
    - curl
    - libexpat1-dev
    - libegl1-mesa-dev
    - libgl1-mesa-dev
    - libssl-dev
    - qtbase5-dev
    - tar
    - zlib1g-dev
    source: http://www.makemkv.com/download/makemkv-oss-x.xx.x.tar.gz
    override-pull: |
      VERSION="$(curl --silent --show-error --location \
        'https://makemkv.com/forum/viewtopic.php?f=3&t=224' \
        | grep -E 'https?://www.makemkv.com/download/makemkv-bin-[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' \
        | head -n1 | sed -E -e \
          's|^.*\"https?://www.makemkv.com/download/makemkv-bin-([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz\".*|\1|')"
      echo "Setting snap version to '$VERSION'"
      snapcraftctl set-version "$VERSION"
      echo "$VERSION" > version

      curl --silent --show-error --location "https://www.makemkv.com/download/makemkv-oss-$VERSION.tar.gz" | tar xz --strip-components=1
      patch -Np1 -i "$SNAPCRAFT_STAGE/patch.diff"
    override-build: |
      sed -i 's|Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/makemkv.png|' makemkvgui/share/makemkv.desktop
      snapcraftctl build
      cp version $SNAPCRAFT_PART_INSTALL/version
    autotools-configure-parameters:
    - --prefix=/usr
    stage-packages:
    - libegl1-mesa
    - libexpat1
    - libgconf-2-4
    - libgl1-mesa-glx
    - libgles2-mesa
    - libqt5core5a
    - libqt5dbus5
    - libqt5gui5
    - libqt5widgets5
    - libqt5waylandclient5
    - libssl1.1
    - libvulkan1
    - libwayland-client0
    - libwayland-cursor0
    - libx11-6
    - lsscsi
    - mesa-vulkan-drivers
    - zlib1g
    prime:
    - -bin/ffmpeg
    - -bin/ffprobe
    - -lib/$SNAPCRAFT_ARCH_TRIPLET/libfdisk.so*
    - -sbin
    - -version

  makemkv-bin:
    after: [makemkv-oss]
    plugin: make
    build-packages:
    - openjdk-11-jre-headless # used to work out the right symlink dir in `override-build`
    - execstack
    source: http://www.makemkv.com/download/makemkv-bin-x.xx.x.tar.gz
    override-pull: |
      curl --silent --show-error --location "http://www.makemkv.com/download/makemkv-bin-$(cat "$SNAPCRAFT_STAGE/version").tar.gz" | tar xz --strip-components=1
    override-build: |
      mkdir tmp && touch tmp/eula_accepted
      execstack -c bin/amd64/makemkvcon
      execstack -c bin/i386/makemkvcon

      snapcraftctl build

      JDK=$(find /usr/lib/jvm -type d -name "java-11-openjdk-*" | head -n1 | xargs basename)
      JDKBIN=../lib/jvm/$JDK/bin
      for exec in java javaws jexec jjs; do
        ln -sf $JDKBIN/$exec $SNAPCRAFT_PART_INSTALL/usr/bin/$exec
      done

      mv $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon.real
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon
      #!/bin/sh
      exec \$SNAP/bin/snapcraft-preload /usr/bin/makemkvcon.real "\$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon

      mv $SNAPCRAFT_PART_INSTALL/usr/bin/wget $SNAPCRAFT_PART_INSTALL/usr/bin/wget.real
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/usr/bin/wget
      #!/bin/sh
      exec \$SNAP/usr/bin/wget.real --no-config "\$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/wget
    stage:
    - -usr/lib/jvm/java-11-openjdk-*/lib/security/cacerts
    organize:
      usr/share/MakeMKV: usr/share/MakeMKV.dist
    stage-packages:
    - libedit2
    - libjpeg-turbo8
    - libtinfo5
    - openjdk-11-jre-headless
    - wget

  cleanup:
    after:
    - libav
    - makemkv-bin
    - makemkv-oss
    - scripts
    - snapcraft-preload
    plugin: nil
    # build-snaps: [kde-frameworks-5-core18]  # List all content-snaps you're using here
    override-prime: |
      set -eux
      # for snap in "kde-frameworks-5-core18"; do  # List all content-snaps you're using here
      #   cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      # done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
